{{ if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.serviceNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.taskNamespace }}
{{ end }}
