apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "go-app.fullname" . }}
  {{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.taskNamespace }}
  {{- end }}
  labels:
    {{- include "go-app.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "go-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "go-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          {{ range .Values.taskCommand }}
          - {{ . }}
          {{ end }}
          env:
          - name: VTT_DBUSER
            value: {{ .Values.db.user }}
          - name: VTT_DBPASSWORD
            value: {{ .Values.db.password }}
          - name: VTT_DBNAME
            value: {{ .Values.db.name }}
          - name: VTT_DBPORT
            value: "{{ .Values.db.port }}"
          - name: VTT_DBHOST
            value: {{ .Values.db.host }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
